- block:
  - name: aliases | template > Generate {{ path_aliases }}
    template:
      src:  aliases.sh
      dest: "{{ path_aliases }}"
      mode: "0600"
    with_subelements:
      - "{{ user }}"
      - shell.aliases
      - skip_missing: true

  tags: aliases, shell_aliases
