- block:
  # entry point where xorg starts or wayland
  - name: bash | template > generate ~/.profile
    template:
      src:  profile.sh.j2
      dest: $HOME/.profile

  when: shell == "bash"
  tags: bash
