- block:
  - name: ({{ item.name }}) bash | package > install dependencies
    package:
      name: "{{ _pkg_bash }}"
    loop:
      - bash
    loop_control:
      loop_var: _pkg_bash
    # run_once: true

  - name: ({{ item.name }}) bash | blockinfile > add exports
    blockinfile:
      path:   "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_exports }}"
      create: true
      marker: "# {mark} bash"
      block: |
        export BASH_ENV="$HOME/{{ path_bash }}/bashrc"
        export BASHRC="$SHELLRC/bash"
        export HISTFILE="$HOME/{{ path_cache }}/bash_history"

  - name: ({{ item.name }}) bash | file > create config dir
    file:
      path:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_bash }}"
      state: directory

  - name: ({{ item.name }}) bash | copy > config files
    copy:
      src:   "{{ role_path }}/files/bash/"
      dest:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_bash }}"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"

  when:
    - item.shell is not defined or item.shell == "bash"
    - item.shell_managed | default(true)
  tags: bash
