- block:
  - name: shell | {{ _user.name }} | template > generate aliases.sh
    template:
      src:  "{{ item }}.j2"
      dest: "{{ path_shell }}/{{ item }}"
      mode: 0600
    loop:
      - aliases.sh
    tags: aliases

  - name: shell | {{ _user.name }} | blockinfile > generate exports
    ansible.builtin.blockinfile:
      path:   "{{ path_exports }}"
      create: yes
      marker: "# {mark} {{ item.name }}"
      block: |
        {% for export in item | dict2items(key_name="key", value_name="value") %}
          {%- if export.key != "name" %}
            {%- if export.value | regex_search("\$\(") +%}  {# when item.value start by $(command) then don't add quotes #}
        export {{ export.key }}={{ export.value }}
            {%- else +%}
        export {{ export.key }}="{{ export.value }}"
            {%- endif %}
          {%- endif %}
        {% endfor %}
    with_items: #"
      - "{{ exports_path   }}"
      - "{{ exports_apps   }}"
      - "{{ exports_gui    }}"
      - "{{ exports_xdg    }}"
      - "{{ exports_others }}"
    tags: exports

  when: _user.name != root
