- block:
  - name: functions | file > Create {{ path_shell }}/functions dir
    file:
      path:  "{{ path_shell }}/functions"
      state: directory
      mode:  "0700"

  - name: scripts | copy > Deploy functions on {{ path_shell }}/functions
    copy:
      src:  "{{ item.1 }}/"
      dest: "{{ path_shell }}/functions"
      mode: "0600"
    with_subelements:
      - "{{ user }}"
      - shell.functions
      - skip_missing: true

  tags: shell_functions
