- block:
  - name: functions | file > create {{ path_shell }}/functions dir
    file:
      path:  "{{ path_shell }}/functions"
      state: directory
      mode:  "0700"

  - name: scripts | copy > deploy functions on {{ path_shell }}/functions
    copy:
      src:  "{{ item }}/"
      dest: "{{ path_shell }}/functions"
      mode: "0600"
    loop: "{{ shell_functions }}"

  tags: shell_functions
