- block:
  - name: history | file > create atuin config & cloud dirs
    file:
      path:  "{{ item }}/atuin"
      state: directory
    with_items:
      - "{{ path_share_cloud }}"
      - "{{ path_config }}"

  - name: history | package > install dependencies
    package:
      name: "{{ item }}"
    loop:
      - atuin
    become_user: "{{ root }}"

  - name: history | template > generate atuin config file
    template:
      src:  atuin_config.toml
      dest: "{{ path_config }}/atuin/config.toml"

  tags: history, atuin
