- block:
  - name: home_dirs | file > Create user directories
    file:
      path:  "{{ item }}"
      state: directory
    loop:
      - "{{ path_config        }}"
      - "{{ path_local         }}"
      - "{{ path_cache         }}"
      - "{{ path_logs          }}"
      - "{{ path_shell         }}"
      - "{{ path_ssh           }}"
      - "{{ path_systemd_user  }}"
      - "{{ path_src           }}"
      - "{{ path_scripts       }}"
      - "{{ path_bin           }}"
      - "{{ path_share         }}"
      - "{{ path_cache_aur     }}"
      - "{{ path_cache_ansible }}"
      - "{{ path_share_cloud   }}"

  tags: user_dirs
