- block:
  - import_tasks: home_dirs.yml

  - import_tasks: sources.yml

  - import_tasks: packages.yml

  - import_tasks: functions.yml

  # - import_tasks: scripts.yml

  # - import_tasks: exports.yml

  # - import_tasks: aliases.yml

  # - import_tasks: profile.yml   ## normalement plus utile

  # - include_tasks: zsh.yml
  #   loop: "{{ user }}"
  #   tags: zsh

  # - include_tasks: bash.yml
  #   loop: "{{ user }}"
  #   tags: bash

  # - import_tasks: prompt.yml

  # - import_tasks: history.yml

  # ## A DEPLACER AUTRE ROLE
  # # - import_tasks: motd.yml
  # # - name: banner | Configure banner welcome file
  # #   when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and shell_cygwin_enabled == false
  # #   copy: src=11-welcome dest=/etc/update-motd.d/11-welcome owner={{ shell_owner }} group={{ shell_group }} mode=0755

  become_user: "{{ default_user }}"
  tags: shell
