
# - name: "[include_vars] aliases.yml, exports.yml, icons.yml"
#   include_vars:
#     dir: vars

- block:
  - name: "[file] [{{ user[inventory_hostname].1.name }}] create {{ path.shell }}"
    file:
      path:  "{{ path.shell }}"
      state: directory
      mode:  0700
      # mode:  0750            ## essayer de le réduire

  - name: "[template] [{{ user[inventory_hostname].1.name }}] copy exports, aliases ans icons on {{ path.shell }}/"
    loop:
      - exports
      - aliases
      - icons
    template:
      src:  "{{ item }}.j2"
      dest: "{{ path.shell }}/{{ item }}.sh"
      mode: 0600
      # mode: "0640"

  - name: "[template] [{{ user[inventory_hostname].1.name }}] copy profile.zsh on {{ path.shell }}/profile.sh"
    template:
      src:  profile.j2
      dest: "{{ path.shell }}/profile.sh"
      mode: 0600
      # mode: "0640"            ## essayer réduire en 600 max

  become: yes
  become_user: "{{ user[inventory_hostname].1.name }}"

- block:
  - name: "[file] [{{ user[inventory_hostname].0.name }}] create {{ path.shell }}"
    file:
      path:  "{{ path.shell }}"
      state: directory
      mode:  0700
      # mode:  "0750"            ## essayer de le réduire

  ## supprimer exports_root.j2 et aliases_root.j2 ?
  - name: "[template] [{{ user[inventory_hostname].0.name }}] copy exports, aliases on {{ path.shell }}"
    loop:
      - exports
      - aliases
    template:
      src:  "{{ item }}.j2"
      dest: "{{ path.shell }}/{{ item }}.sh"
      mode: 0600
      # mode: "0640"

  - name: "[template] [{{ user[inventory_hostname].0.name }}] copy profile.zsh on $HOME/.zshrc"
    template:
      src:  profile_root.j2
      # dest: "{{ path.shell }}/profile.sh"
      dest: "$HOME/.zshrc"
      mode: 0600
      # mode: "0640"            ## essayer réduire en 600 max

  become: yes
  become_user: "{{ user[inventory_hostname].0.name }}"

- include: zsh.yml

