- block:
  - include_tasks: for_each_user.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: i_user

  - include_tasks: shell.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: i_user

  - include_tasks: exports_and_aliases.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: i_user
    tags:

  - import_tasks: zsh.yml

  - import_tasks: bash.yml

  - import_tasks: prompt.yml

  - import_tasks: history.yml

  become_user: "{{ default_user }}"
  tags: shell, exports, aliases
