- block:
  - name: include_vars > shell/vars/*
    include_vars:
      dir: vars
      extensions: ['yml']
    tags: exports, aliases

  - include_tasks: shell.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: _user

  - include_tasks: exports_aliases.yml
    loop: "{{ user }}"
    loop_control:
      loop_var: _user
    tags: exports, aliases

  - ansible.builtin.import_tasks: zsh.yml
  # - ansible.builtin.import_tasks: bash.yml      ## TODO

  - ansible.builtin.import_tasks: prompt.yml

  - ansible.builtin.import_tasks: history.yml

  # - include_tasks: bash.yml

  become_user: "{{ default_user }}"
  tags: shell
