- block:
  - name: ({{ user.1.name }}) oh-my-zsh | stat > check if oh-my-zsh repo present
    stat:
      path: "{{ path_zsh }}/oh-my-zsh"
    register: _ohmyzsh

  - name: ({{ user.1.name }}) oh-my-zsh | git > clone oh-my-zsh on {{ path_zsh }}
    git:
      repo:  https://github.com/robbyrussell/oh-my-zsh
      dest:  "{{ path_zsh }}/oh-my-zsh"
      depth: 1
    when: not _ohmyzsh.stat.exists

  - name: ({{ user.1.name }}) oh-my-zsh | file > remove oh-my-zsh/lib/{directories,grep-alias}
    file:
      path: "{{ path_zsh }}/oh-my-zsh/lib/{{ item }}"
      state: absent
    loop:
      - directories.zsh
      - grep-alias.zsh

  - name: ({{ user.1.name }}) oh-my-zsh | file > set permissions of oh-my-zsh
    file:
      path:    "{{ path_zsh }}/oh-my-zsh"
      mode:    go-w
      recurse: yes

  when:
    - shell == "zsh"
    - oh-my-zsh | default(false)
  tags: oh-my-zsh
