- block:
  - name: package > intall dependencies
    package:
      name: "{{ item }}"
    loop:
      - exa
      - bat
      - fd
      - fzf
      # - { name: mawk, state: absent  }  # must not be installed for zplug
    become_user: root

  tags: shell_packages
