- block:
  - name: profile | file > Create /etc/zsh dir
    file:
      path:  /etc/zsh
      state: directory
    become_user: root

  - name: profile | template > Generate global bashrc and zprofile
    template:
      src:  "{{ item.src  }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: etc_bashrc,   dest: /etc/bash.bashrc  }
      - { src: etc_zprofile, dest: /etc/zsh/zprofile }
      - { src: etc_zshenv,   dest: /etc/zsh/zshenv   }
    become_user: root

  - name: profile | template > Generate shell profile
    template:
      src:  profile.sh
      dest: "{{ path_shell }}/profile.sh"

  tags: shell_profile, profile
