- block:
  - name: prompt | package > Install starship
    package:
      name: starship
    become_user: root

  - name: prompt | file > Create starship config dir
    file:
      path:  "{{ path_config }}/starship"
      state: directory

  - name: prompt | template > Generate starship config file
    template:
      src:  starship.toml
      dest: "{{ path_config }}/starship/config.toml"

  when: shell_prompt == "starship"
  tags: prompt, starship, shell_prompt
