- block:
  - name: prompt | package > install dependencies
    package:
      name: "{{ item }}"
    loop:
      - starship

  - name: prompt | file > create starship config dir
    file:
      path:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + path_config }}/starship"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
      state: directory
    when: item.shell_managed | default(true)
    loop: "{{ user }}"

  - name: prompt | template > generate starship config file
    template:
      src:   config_starship.toml
      dest:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + path_config }}/starship/config.toml"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
    when: item.shell_managed | default(true)
    loop: "{{ user }}"

  tags: prompt, starship
