- block:
  - name: prompt | package > install dependencies
    package:
      name: "{{ item }}"
    loop:
      - starship

  - name: prompt | file > create starship config dir
    file:
      path:  "{{ path_config }}/starship"
      state: directory

  - name: prompt | template > generate starship config file
    template:
      src:  starship_config.toml.j2
      dest: "{{ path_config }}/starship/config.toml"
    tags: starship_template

  tags: prompt, starship_template
