- block:
  - name: scripts | file > create user local/bin dir
    file:
      # path:  "{{ ('/root' if item.owner == 'root' else ('/home/' + item.owner)) + '/' + item.dest }}"
      path:  "{{ item.dest }}"
      state: directory
      mode:  0700
    loop: "{{ shell_scripts }}"

  - name: scripts | copy > deploy scripts on local/bin
    copy:
      src:   "{{ item.1 }}/"
      # dest:  "{{ ('/root' if item.0.owner == 'root' else ('/home/' + item.0.owner)) + '/' + item.0.dest }}"
      dest:  "{{ item.0.dest }}"
    with_subelements:
      - "{{ shell_scripts }}"
      - src

  - name: scripts | file > change user/group and make scripts executables
    file:
      # path:    "{{ ('/root' if item.0.owner == 'root' else ('/home/' + item.0.owner)) + '/' + item.0.dest }}"
      path:    "{{ item.0.dest }}"
      owner:   "{{ item.0.owner }}"
      group:   "{{ item.1.group | default(item.1.name) }}"
      mode:    "0700"
      recurse: true
    when: item.0.owner == item.1.name
    with_nested:
      - "{{ shell_scripts }}"
      - "{{ user }}"

  tags: shell_scripts, local_bin
