- block:
  - name: scripts | file > Create user {{ path_scripts }} dir
    file:
      path:  "{{ path_scripts }}"
      state: directory
      mode:  "0700"

  - name: scripts | copy > Deploy scripts on {{ path_scripts }}/
    copy:
      src:  "{{ item.1 }}/"
      dest: "{{ path_scripts }}"
      mode: "0700"
    with_subelements:
      - "{{ user }}"
      - shell.scripts
      - skip_missing: true

  tags: shell_scripts, local_bin
