- block:
  - name: scripts | file > Create user {{ path_scripts }} dir
    file:
      path:  "{{ path_scripts }}"
      state: directory
      mode:  "0700"

  - name: scripts | copy > deploy scripts on local/bin
    copy:
      src:  "{{ item }}/"
      dest: "{{ path_scripts }}"
      mode: "0700"
    loop: "{{ shell_scripts }}"

  tags: shell_scripts, local_bin
