- block:
  - name: package > intall dependencies
    package:
      name: "{{ item }}"
    with_items:
      - exa
      - bat

  - name: shell | user > check user exists
    user:
      name:  "{{ item.name }}"
      state: present
    loop: "{{ user }}"

  - name: shell | file > create user shell dir
    file:
      path:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_shell }}"
      owner: "{{ item.name }}"
      state: directory
      mode:  0700
    loop: "{{ user }}"

  # old
  # - name: shell | {{ i_user.name }} | template > deploy icons.sh, inputrc on {{ path_shell }}
  #   template:
  #     src:  "{{ item }}.j2"
  #     dest: "{{ path_shell }}/{{ item }}"
  #     mode: 0600
  #   loop:
  #     - icons.sh
  #     - sources.sh
  #     - inputrc
