- block:
  - name: shell | user > check user exists
    user:
      name:  "{{ item.name }}"
      state: present
    loop: "{{ user }}"

  - name: shell | file > create user shell dir
    file:
      # path:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_shell }}"
      path:  "{{ path_shell }}"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
      state: directory
      mode:  "0700"
    loop: "{{ user }}"

  - name: shell | template > generate sources.sh
    template:
      src:   sources.sh
      # dest:  "{{ ('/root' if item.name == 'root' else ('/home/' + item.name)) + '/' + path_shell + '/sources.sh' }}"
      dest:  "{{ path_shell }}/sources.sh"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
    loop: "{{ user }}"

  # old A DELETE
  # - name: shell | {{ i_user.name }} | template > deploy icons.sh, inputrc on {{ path_shell }}
  #   template:
  #     src:  "{{ item }}.j2"
  #     dest: "{{ path_shell }}/{{ item }}"
  #     mode: 0600
  #   loop:
  #     - icons.sh
  #     - sources.sh
  #     - inputrc
