- block:
  - name: zsh | package > Install dependencies
    package:
      name: "{{ item }}"
    loop:
      - zsh
      - git     # for clone repo zplug
    become_user: root

  - name: zsh | file > Create zsh config dir
    file:
      path:  "{{ path_zsh }}"
      state: directory

  ## KO
  # - name: ({{ item.name }}) zsh | template > export zsh scripts
  #   template:
  #     src:  "{{ item }}"
  #     dest: "{{ path_zsh + '/' + (item | basename) }}"
  #     mode: "0600"
  #   with_fileglob:
  #     - ../templates/zsh/*

  - name: zsh | template > Generate zshrc
    template:
      src:  zshrc
      dest: "{{ path_zsh }}/zshrc"
      mode: "0600"

  - name: zsh | stat > Check if zplug repo present
    stat:
      path: "{{ path_zsh }}/zplug"
    register: _zplug

  - name: zsh | git > Clone zplug on {{ path_zsh }}/zplug
    git:
      repo:  https://github.com/zplug/zplug
      dest:  "{{ path_zsh }}/zplug"
      depth: 1
    when: not _zplug.stat.exists

  - name: zsh | copy > Config files
    copy:
      src:  "{{ role_path }}/files/zsh/"
      dest: "{{ path_zsh }}"

  tags: zsh
