# todo
#   https://github.com/ericmurphyxyz/archrice/tree/master/.config/zsh
- block:
  - name: zsh | pacman > install packages
    pacman:
      name:  "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: git,  state: present }
      - { name: zsh,  state: present }
      - { name: mawk, state: absent  }  # must not be installed for zplug

  - name: zsh | template > generate zshenv dot file
    template:
      src:  profile.sh.j2    # needed by st terminal in hyprland, because source exports in profile.sh is load in a wayland instance ?
      dest: $HOME/.zshenv

  - name: zsh | blockinfile > add exports
    blockinfile:
      path:   "{{ path_exports }}"
      marker: "# {mark} zsh"
      block: |
        {% for item in exports_zsh | dict2items(key_name="export", value_name="value") %}
          export {{ item.export }}={{ item.value }}
        {% endfor %}

  ## A DELETE IS OK quand le fichier n'existe pas
  # - name: "[zsh] [stat] [{{ user.1.name }}] check if .cache/zsh/history exists"
  #   stat:
  #     path: "$HOME/.cache/zsh/history"
  #   register: _zsh_history

  # superseeded by atuin
  #- name: zsh | file > create zsh file history
  #  file:
  #    path: "$HOME/.cache/{{ item.path }}"
  #    state: "{{ item.state }}"
  #  loop:
  #    - { path: zsh,         state: directory }
  #    - { path: zsh/history, state: touch     }
  #    #old: - { path: zsh/history, state: file }
  #  # when: not _zsh_history.stat.exists

  - name: zsh | file > create zsh parent directory
    file:
      path:  "{{ path_zsh }}"
      state: directory

  - name: zsh | template > export zsh scripts
    template:
      src:  "{{ item }}"
      dest: "{{ path_zsh + '/' + (item | basename) }}"
      mode: "0600"
    with_fileglob:
      - ../templates/zsh/*

  - name: zsh | template > generate .zshrc
    template:
      src:  zshrc.j2
      dest: "{{ path_zsh }}/.zshrc"
      mode: 0600

  - name: zsh | stat > check if zplug repo present
    stat:
      path: "{{ path_zsh }}/zplug"
    register: _zplug

  - name: zsh | git > clone zplug on {{ path_zsh }}/zplug/
    git:
      repo:  https://github.com/zplug/zplug
      dest:  "{{ path_zsh }}/zplug"
      depth: 1
    when: not _zplug.stat.exists

  - import_tasks: oh-my-zsh.yml

  tags: zsh
