- block:
  - name: zsh | package > install dependencies
    package:
      name:  "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: git,  state: present }
      - { name: zsh,  state: present }
      - { name: mawk, state: absent  }  # must not be installed for zplug

  - name: zsh | file > create zsh config dir
    file:
      path:  "{{ path_zsh }}"
      state: directory

  - name: zsh | template > export zsh scripts
    template:
      src:  "{{ item }}"
      dest: "{{ path_zsh + '/' + (item | basename) }}"
      mode: "0600"
    with_fileglob:
      - ../templates/zsh/*

  - name: zsh | template > generate .zshrc
    template:
      src:  zshrc.j2
      dest: "{{ path_zsh }}/.zshrc"
      mode: 0600

  - name: zsh | stat > check if zplug repo present
    stat:
      path: "{{ path_zsh }}/zplug"
    register: _zplug

  - name: zsh | git > clone zplug on {{ path_zsh }}/zplug/
    git:
      repo:  https://github.com/zplug/zplug
      dest:  "{{ path_zsh }}/zplug"
      depth: 1
    when: not _zplug.stat.exists

  - import_tasks: oh-my-zsh.yml

  tags: zsh
