- block:
  - name: ({{ item.name }}) zsh | file > create zsh config dir
    file:
      path:  "{{ path_zsh }}"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"

  - name: ({{ item.name }}) zsh | template > export zsh scripts
    template:
      src:  "{{ item }}"
      dest: "{{ path_zsh + '/' + (item | basename) }}"
      mode: "0600"
    with_fileglob:
      - ../templates/zsh/*

  - name: ({{ item.name }}) zsh | template > generate .zshrc
    template:
      src:   zshrc
      dest:  "{{ path_zsh }}/zshrc"
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
      mode:  "0600"

  - name: ({{ item.name }}) zsh | stat > check if zplug repo present
    stat:
      path: "{{ path_zsh }}/zplug"
    register: _zplug

  - name: ({{ item.name }}) zsh | git > clone zplug on {{ path_zsh }}/zplug/
    git:
      repo:  https://github.com/zplug/zplug
      dest:  "{{ path_zsh }}/zplug"
      depth: 1
    when: not _zplug.stat.exists

  - name: ({{ item.name }}) zsh | file > blabla
    file:
      path:  "{{ path_zsh }}/zplug"
      state: directory
      owner: "{{ item.name }}"
      group: "{{ item.group | default(item.name) }}"
      mode:  "0755"           # keep always double quotes

  # - import_tasks: oh-my-zsh.yml

  when: item.shell == "zsh"
