#!/usr/bin/env bash

source $SHELLRC/aliases.sh
# export SHELLRC="$HOME/.config/shell"
# source "$SHELLRC/exports.sh"
# source "$SHELLRC/aliases.sh"
# source "$SHELLRC/icons.sh"

for file in $SHELLRC/functions/*; do
  source $file
done

if command -v atuin &> /dev/null; then
  source $BASHRC/bash-preexec.sh
  eval "$(atuin init bash)"
fi

# shopt -u autocd
# shopt -u assoc_expand_once
# shopt -u cdable_vars
# shopt -u cdspell
# shopt -u checkhash
# shopt -u checkjobs
# shopt -s checkwinsize

# blk='\[\033[01;30m\]'   # Black
# red='\[\033[01;31m\]'   # Red
# grn='\[\033[01;32m\]'   # Green
# ylw='\[\033[01;33m\]'   # Yellow
# blu='\[\033[01;34m\]'   # Blue
# pur='\[\033[01;35m\]'   # Purple
# cyn='\[\033[01;36m\]'   # Cyan
# wht='\[\033[01;37m\]'   # White
# clr='\[\033[00m\]'      # Reset

# set -o vi
