# alias -s {js,json,env,md,html,css,toml}=cat
alias -s txt=$EDITOR
alias -s pdf="devour zathura"
alias -s epub="devour zathura"
alias -s png=firefox
# alias -s jpg=
alias -s gif="sxiv -a"
alias -s mkv="devour mpv"
alias -s webm="devour mpv"
alias -s ods=libreoffice
alias -s odg=libreoffice
alias -s odt=libreoffice
alias -s gif="sxiv -a"
alias -s gif="sxiv -a"
alias -s gif="sxiv -a"
alias -s gif="sxiv -a"
alias -s md="glow -p"
alias -s sh=$EDITOR
alias -s c=$EDITOR
