db_path = "$SHARE/atuin/history.db"   # DB location
search_mode = "fuzzy"                 # search mode: prefix, fulltext, fuzzy
enter_accept = true                   # immediately executing a commandn, press tab to return to the shell

# encryption key directory
# key_path = "~/.key"

# auth session token directory
# session_path = "~/.key"

# date format: us, uk
# dialect = "uk"

# enable/disable automatic sync
# auto_sync = true

# run sync X minutes after running a commmand
# 0 = sync after every command
# sync_frequency = "5m"

# address of the sync server
# sync_address = "https://api.atuin.sh"
