# DB location
db_path = "{{ path_share_cloud }}/atuin/history.db"

# search mode: prefix, fulltext, fuzzy
search_mode = "fuzzy"

# encryption key directory
# key_path = "~/.key"

# auth session token directory
# session_path = "~/.key"

# date format: us, uk
# dialect = "uk"

# enable/disable automatic sync
# auto_sync = true

# run sync X minutes after running a commmand
# 0 = sync after every command
# sync_frequency = "5m"

# address of the sync server
# sync_address = "https://api.atuin.sh"
