# zshrc is empty by default
autoload -U colors && colors	      # enable colors, must be before prompt.zsh

# source $SHELLRC/sources.sh
source $ZSHRC/history.zsh
# source $ZSHRC/prompt.zsh
source $ZSHRC/options.zsh
source $SHELLRC/zsh/bindkeys.zsh
source $SHELLRC/zsh/suffix_aliases.zsh
# source $SHELLRC/zsh/reveal_alias.zsh
# source $SHELLRC/zsh/oh-my-zsh.zsh
# source $SHELLRC/zsh/plugins.zsh

source $LOCAL/repo/git-subrepo/.rc

eval "$(thefuck --alias)"
eval "$(starship init zsh)"
# eval $(thefuck --yeah --alias)
# eval $(thefuck --alias FUCK)

# auto/tab complete
autoload -Uz compinit
# zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'    # case-insensitive completion
zstyle ':completion:*' completer _expand_alias _complete _ignored _files
zstyle ':completion:*' regular true
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)		# to include hidden files because not enable by default
# # Shell Auto-completion
# ## pacman -Sy bash-completion
# autoload -U +X compinit && compinit
# autoload -U +X bashcompinit && bashcompinit
# eval "$(stack --bash-completion-script stack)"

# BEGIN Change cursor shape for different vi modes
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'

  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q'                           # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;}            # Use beam shape cursor for each new prompt.
# END

# enable colors when typing in the command line, must be at the end of zshrc
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh 2> /dev/null
